title: Jacob R. Williams
logo: /assets/img/headshot.png
description: Experienced Machine Learning Engineer proficient in Healthcare Data Analytics and Recommendation Systems
#show_downloads: true
theme: jekyll-theme-minimal
